package DDS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ReliabilityEnumeration extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ReliabilityEnumeration() {
    super(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c5eL, "ReliabilityEnumeration", "r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/8311581661575187550");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_RELIABLE_0 = new EnumerationDescriptor.MemberDescriptor("RELIABLE", "RELIABLE", 0x7358ab7c0bd70c5fL, "r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/8311581661575187551");
  private final EnumerationDescriptor.MemberDescriptor myMember_BEST_EFFORT_0 = new EnumerationDescriptor.MemberDescriptor("BEST_EFFORT", "BEST_EFFORT", 0x7358ab7c0bd70c60L, "r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/8311581661575187552");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c5eL, 0x7358ab7c0bd70c5fL, 0x7358ab7c0bd70c60L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_RELIABLE_0, myMember_BEST_EFFORT_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_RELIABLE_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "RELIABLE":
        return myMember_RELIABLE_0;
      case "BEST_EFFORT":
        return myMember_BEST_EFFORT_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
