package DDS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_HistoryEnumeration extends EnumerationDescriptorBase {

  public EnumerationDescriptor_HistoryEnumeration() {
    super(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c64L, "HistoryEnumeration", "r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/8311581661575187556");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_KEEP_LAST_0 = new EnumerationDescriptor.MemberDescriptor("KEEP_LAST", "KEEP_LAST", 0x7358ab7c0bd70c65L, "r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/8311581661575187557");
  private final EnumerationDescriptor.MemberDescriptor myMember_KEEP_ALL_0 = new EnumerationDescriptor.MemberDescriptor("KEEP_ALL", "KEEP_ALL", 0x7358ab7c0bd70c66L, "r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/8311581661575187558");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c64L, 0x7358ab7c0bd70c65L, 0x7358ab7c0bd70c66L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_KEEP_LAST_0, myMember_KEEP_ALL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_KEEP_LAST_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "KEEP_LAST":
        return myMember_KEEP_LAST_0;
      case "KEEP_ALL":
        return myMember_KEEP_ALL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
