package DDS.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DDS_Deadline = 0;
  public static final int DDS_Depth = 1;
  public static final int DDS_Durability = 2;
  public static final int DDS_History = 3;
  public static final int DDS_LeaseDuration = 4;
  public static final int DDS_Lifespan = 5;
  public static final int DDS_Liveliness = 6;
  public static final int DDS_Reliability = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x331f7a18c6574dd7L, 0x870742124f20f67bL);
    builder.put(0x69023be9ff596d71L, DDS_Deadline);
    builder.put(0x69023be9ff596d90L, DDS_Depth);
    builder.put(0x4bc2f2a09e3862bdL, DDS_Durability);
    builder.put(0x4bc2f2a09e3b8fa4L, DDS_History);
    builder.put(0x69023be9ff596dadL, DDS_LeaseDuration);
    builder.put(0x69023be9ff596dcbL, DDS_Lifespan);
    builder.put(0x4bc2f2a09e3b8fc1L, DDS_Liveliness);
    builder.put(0x4bc2f2a09e3b8fe4L, DDS_Reliability);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
