package DDS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDDS_Deadline = createDescriptorForDDS_Deadline();
  /*package*/ final ConceptDescriptor myConceptDDS_Depth = createDescriptorForDDS_Depth();
  /*package*/ final ConceptDescriptor myConceptDDS_Durability = createDescriptorForDDS_Durability();
  /*package*/ final ConceptDescriptor myConceptDDS_History = createDescriptorForDDS_History();
  /*package*/ final ConceptDescriptor myConceptDDS_LeaseDuration = createDescriptorForDDS_LeaseDuration();
  /*package*/ final ConceptDescriptor myConceptDDS_Lifespan = createDescriptorForDDS_Lifespan();
  /*package*/ final ConceptDescriptor myConceptDDS_Liveliness = createDescriptorForDDS_Liveliness();
  /*package*/ final ConceptDescriptor myConceptDDS_Reliability = createDescriptorForDDS_Reliability();
  /*package*/ final EnumerationDescriptor myEnumerationDurabilityEnumeration = new EnumerationDescriptor_DurabilityEnumeration();
  /*package*/ final EnumerationDescriptor myEnumerationHistoryEnumeration = new EnumerationDescriptor_HistoryEnumeration();
  /*package*/ final EnumerationDescriptor myEnumerationLivelinessEnumeration = new EnumerationDescriptor_LivelinessEnumeration();
  /*package*/ final EnumerationDescriptor myEnumerationReliabilityEnumeration = new EnumerationDescriptor_ReliabilityEnumeration();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x6d22281353ea440eL, 0xba3023ced4b723f0L, "QoS");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDDS_Deadline, myConceptDDS_Depth, myConceptDDS_Durability, myConceptDDS_History, myConceptDDS_LeaseDuration, myConceptDDS_Lifespan, myConceptDDS_Liveliness, myConceptDDS_Reliability);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.DDS_Deadline:
        return myConceptDDS_Deadline;
      case LanguageConceptSwitch.DDS_Depth:
        return myConceptDDS_Depth;
      case LanguageConceptSwitch.DDS_Durability:
        return myConceptDDS_Durability;
      case LanguageConceptSwitch.DDS_History:
        return myConceptDDS_History;
      case LanguageConceptSwitch.DDS_LeaseDuration:
        return myConceptDDS_LeaseDuration;
      case LanguageConceptSwitch.DDS_Lifespan:
        return myConceptDDS_Lifespan;
      case LanguageConceptSwitch.DDS_Liveliness:
        return myConceptDDS_Liveliness;
      case LanguageConceptSwitch.DDS_Reliability:
        return myConceptDDS_Reliability;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationDurabilityEnumeration, myEnumerationHistoryEnumeration, myEnumerationLivelinessEnumeration, myEnumerationReliabilityEnumeration);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDDS_Deadline() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_Deadline", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596d71L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Deadline", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba267L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/7566676200133324145");
    b.version(2);
    b.property("value", 0x69023be9ff596d74L).type(PrimitiveTypeId.INTEGER).origin("7566676200133324148").done();
    b.alias("Deadline (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_Depth() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_Depth", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596d90L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Depth", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba264L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/7566676200133324176");
    b.version(2);
    b.property("value", 0x69023be9ff596d91L).type(PrimitiveTypeId.INTEGER).origin("7566676200133324177").done();
    b.alias("Depth (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_Durability() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_Durability", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x4bc2f2a09e3862bdL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Durability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba266L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/5459192469989647037");
    b.version(2);
    b.property("value", 0x4bc2f2a09e3862beL).type(MetaIdFactory.dataTypeId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c69L)).origin("5459192469989647038").done();
    b.alias("Durability (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_History() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_History", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x4bc2f2a09e3b8fa4L);
    b.class_(false, false, false);
    b.super_("QoS.structure.History", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba263L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/5459192469989855140");
    b.version(2);
    b.property("value", 0x4bc2f2a09e3b8fa5L).type(MetaIdFactory.dataTypeId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c64L)).origin("5459192469989855141").done();
    b.alias("History (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_LeaseDuration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_LeaseDuration", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596dadL);
    b.class_(false, false, false);
    b.super_("QoS.structure.LeaseDuration", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba26aL);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/7566676200133324205");
    b.version(2);
    b.property("value", 0x69023be9ff596daeL).type(PrimitiveTypeId.INTEGER).origin("7566676200133324206").done();
    b.alias("Lease Duration (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_Lifespan() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_Lifespan", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596dcbL);
    b.class_(false, false, false);
    b.super_("QoS.structure.Lifespan", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba268L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/7566676200133324235");
    b.version(2);
    b.property("value", 0x69023be9ff596dccL).type(PrimitiveTypeId.INTEGER).origin("7566676200133324236").done();
    b.alias("Lifespan (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_Liveliness() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_Liveliness", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x4bc2f2a09e3b8fc1L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Liveliness", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba269L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/5459192469989855169");
    b.version(2);
    b.property("value", 0x4bc2f2a09e3b8fc2L).type(MetaIdFactory.dataTypeId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c6eL)).origin("5459192469989855170").done();
    b.alias("Livelines (DDS)");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDDS_Reliability() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DDS", "DDS_Reliability", 0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x4bc2f2a09e3b8fe4L);
    b.class_(false, false, false);
    b.super_("QoS.structure.Reliability", 0x6d22281353ea440eL, 0xba3023ced4b723f0L, 0x6f2f11a0135ba265L);
    b.origin("r:7f874e35-ef79-4b8f-ae49-2ebc5153760e(DDS.structure)/5459192469989855204");
    b.version(2);
    b.property("value", 0x4bc2f2a09e3b8fe5L).type(MetaIdFactory.dataTypeId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x7358ab7c0bd70c5eL)).origin("5459192469989855205").done();
    b.alias("Reliability (DDS)");
    return b.create();
  }
}
