package DDS.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  public ConstraintsDescriptor getConstraints(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new DDS_Deadline_Constraints();
      case 1:
        return new DDS_Depth_Constraints();
      case 2:
        return new DDS_LeaseDuration_Constraints();
      case 3:
        return new DDS_Lifespan_Constraints();
      default:
    }
    return new BaseConstraintsDescriptor(concept);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596d71L), MetaIdFactory.conceptId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596d90L), MetaIdFactory.conceptId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596dadL), MetaIdFactory.conceptId(0x331f7a18c6574dd7L, 0x870742124f20f67bL, 0x69023be9ff596dcbL)).seal();
}
